name: "CI"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v17
      with:
        name: devenv

    - name: Install devenv.sh
      shell: bash
      run: nix profile add nixpkgs#devenv

    - name: Build the devenv shell and run pre-test checks
      run: devenv test

    - name: Compile
      shell: devenv shell -- bash -e {0}
      run: cargo build --locked --release

    - name: Run tests
      shell: devenv shell -- bash -e {0}
      run: cargo test --locked

  nixos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v17
      with:
        name: devenv

    - name: Evaluate the NixOS module
      run: nix --accept-flake-config build .#checks.x86_64-linux.underclass-module

    - name: Run the NixOS machine test
      run: nix --accept-flake-config build .#checks.x86_64-linux.underclass-vm
